spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wy_transit_monitor?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: paradise

jobFlag: 0

server:
  servlet:
    context-path: /transit

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 支持驼峰转换